package e

var MsgFlags = map[int]string{
	SUCCESS:                 "success",
	ERROR:                   "error",
	NOT_MODIFIED:            "not_modified",
	INVALID_PARAMS:          "invalid_params",
	UNAUTHORIZED:            "unauthorized",
	NOT_FOUND:               "not_found",
	UNSUPPORTED_MEDIA_TYPE:  "unsupported_media_type",
	UNPROCESSABLE_ENTITY:    "error",
	INSUFFICIENT_BALANCE:    "insufficient_balance",
	MEMBER_NOT_FOUND:        "member_not_found",
	MEMBER_ACCOUNT_INACTIVE: "member_account_inactive",

	// auth, otp
	ACCESS_TOKEN_NOT_FOUND:                  "access_token_not_found",
	INVALID_PASSWORD:                        "invalid_password",
	PUBLIC_KEY_MISSING:                      "public_key_missing",
	PRIVATE_KEY_MISSING:                     "private_key_missing",
	TOKEN_EXPIRED:                           "token_expired",
	SIGNATURE_VERIFICATION_FAIL:             "signature_verification_failed",
	INVAID_TOKEN_ISSUE_DATE:                 "invalid_token_issue_date",
	INVAID_REFRESH_TOKEN:                    "invalid_refresh_token",
	OTP_EXPIRED:                             "otp_expired",
	OTP_EXCEED_MAX_ATTEMPTS:                 "exceed_max_attempts",
	INVALID_OTP:                             "invalid_otp",
	INVALID_USERNAME_OR_PASSWORD:            "invalid_username_or_password",
	INVALID_USER:                            "invalid_user",
	ACCOUNT_TERMINATED:                      "account_terminated",
	PLEASE_REQUEST_OTP:                      "please_request_otp",
	INVALID_OTP_TYPE:                        "invalid_otp_type",
	INVALID_TOKEN_TYPE:                      "invalid_token_type",
	INVALID_OTP_SEND_TYPE:                   "invalid_otp_send_type",
	INVALID_EMAIL_FORMAT:                    "invalid_email_format",
	EMAIL_IS_REQUIRED:                       "email_is_required",
	COUNTRY_CODE_IS_REQUIRED:                "country_code_is_required",
	MOBILE_NO_IS_REQUIRE:                    "mobile_no_is_required",
	EMPTY_USER_EMAIL_AND_MOBILE:             "empty_email_and_mobile",
	INVALID_JWT_TOKEN_TYPE:                  "invalid_token_type",
	INVAID_SLOT_REFRESH_TOKEN:               "invalid_slot_refresh_token",
	SLOT_ACCESS_TOKEN_NOT_FOUND:             "slot_access_token_not_found",
	GENERATE_ACCESS_TOKEN_ID_ERROR:          "generate_access_token_id_error",
	GENERATE_REFRESH_TOKEN_ID_ERROR:         "generate_refresh_token_id_error",
	GENERATE_SLOT_ACCESS_TOKEN_ID_ERROR:     "generate_slot_access_token_id_error",
	GENERATE_SLOT_REFRESH_TOKEN_ID_ERROR:    "generate_slot_refresh_token_id_error",
	PASSWORD_VALIDATION_ERROR:               "password_must_contain_one_capital_letter_one_number_and_min_8_characters",
	ETAG_RESPONSE_DATA_NOT_FOUND:            "etag_response_data_not_found",
	ETAG_INVALID_RESPONSE_DATA:              "etag_invalid_response_data",
	PLEASE_CHECK_EMAIL_FOR_ACTIVATION_LINK:  "please_check_email_for_activation_link",
	PLEASE_CEHCK_MOBILE_FOR_ACTIVATION_CODE: "please_check_mobile_for_activation_code",
	YOUR_ACCOUNT_IS_LOGIN_AT_ANOTHER_DEVICE: "your_account_is_login_at_another_device",
	OTP_SETTING_NOT_FOUND:                   "otp_setting_not_found",
	OTP_MAX_REQUEST_SETTING_NOT_FOUND:       "otp_setting_not_found",
	OTP_MAX_REQUEST_SETTING_TIME_NOT_FOUND:  "otp_setting_not_found",
	OTP_EXCEED_MAX_REQUEST:                  "otp_requested_too_often",
	PLEASE_CHECK_EMAIL_FOR_OTP_CODE:         "please_check_email_for_otp_code",
	PLEASE_CEHCK_MOBILE_FOR_OTP_CODE:        "please_check_mobile_for_otp_code",
	INVALID_SECONDARY_PIN:                   "invalid_secondary_pin",
	SECONDARY_PIN_VALIDATION_ERROR:          "secondary_pin_must_be_6_digits_number",

	// email / notification / sms
	TO_NAME_LENGHT_MUST_SAME_WITH_TO_EMAIL: "email_to_name_must_match_with_to_email",
	CC_NAME_LENGHT_MUST_SAME_WITH_CC_EMAIL: "email_cc_name_must_match_with_cc_email",
	SEND_MAIL_SUBJECT_CANNOT_EMPTY:         "send_mail_subject_cannot_be_empty",
	SEND_MAIL_MESSAGE_CANNOT_EMPTY:         "send_mail_message_cannot_be_empty",
	SEND_EMAIL_FAIL:                        "send_email_fail",
	SYS_EMAIL_NOT_FOUND:                    "sys_email_not_found",
	INVALID_EMAIL_SETTING:                  "invalid_email_setting",
	SEND_NOTIFICATION_FAILED:               "send_notification_failed",
	JPUSH_APP_KEY_MISSING:                  "app_key_missing",
	JPUSH_MASTER_SECRET_MISSING:            "master_secret_missing",
	JPUSH_URL_MISSING:                      "notification_url_missing",
	NOTFICATION_LABEL_NOT_FOUND:            "notification_label_not_found",
	INVALID_NOTIFICATION_STATUS:            "invalid_notification_status",
	INVALID_NOTIFICATION_ID:                "invalid_notification_id",
	INVALID_NOTIFICATION_MODULE:            "invalid_notification_module",
	INVALID_NOTIFICATION_MODULE_ID:         "invalid_notification_module_id",
	NOTIFICATION_LABEL_IS_REQUIRED:         "notification_label_is_required",
	INVALID_NOTIFICATION_LABEL:             "invalid_notification_label",
	INVALID_NOTIFICATION_MODULE_TYPE:       "invalid_notification_module_type",
	EMPTY_NOTIFICATION_LABEL:               "empty_notification_label",
	NOTIFICATION_ALREADY_SEND:              "notification_already_send",
	SMS_URL_SETTING_NOT_FOUND:              "sms_url_setting_not_found",
	SMS_CLIENT_ID_SETTING_NOT_FOUND:        "sms_client_id_setting_not_found",
	SMS_PRIVATE_KEY_SETTING_NOT_FOUND:      "sms_private_key_setting_not_found",
	SMS_USERNAME_SETTING_NOT_FOUND:         "sms_username_setting_not_found",
	SMS_MEMBER_MOBILE_NO_NOT_FOUND:         "member_mobile_number_not_found",
	SMS_MEMBER_MOBILE_COUNTRY_NOT_FOUND:    "member_mobile_country_not_found",
	SMS_LABEL_NOT_FOUND:                    "sms_label_not_found",
	SMS_INVALID_MODULE:                     "invalid_sms_module",
	SMS_LABEL_IS_REQUIRED:                  "sms_label_is_required",
	SMS_LABEL_INVALID:                      "invalid_sms_label",
	SMS_MODULE_ID_INVALID:                  "invalid_sms_module_id",
	SMS_ID_INVALID:                         "invalid_sms_id",
	SMS_LOG_ID_NOT_FOUND:                   "sms_log_id_not_found",

	// user
	MEMBER_EMAIL_EXISTS:                        "email_exists",
	MEMBER_ALREADY_ACTIVATED:                   "member_already_activated",
	INVALID_MEMBER:                             "invalid_member",
	PASSWORD_MUST_MATCH_CONFIRM_PASS:           "password_must_match_confirm_password",
	INVALID_COUNTRY_CODE:                       "invalid_country_code",
	INVALID_MOBILE_NO:                          "invalid_mobile_no",
	MEMBER_MOBILE_EXISTS:                       "mobile_no_already_registered",
	MEMBER_EMAIL_NOT_FOUND:                     "email_not_found",
	MEMBER_MOBILE_NOT_FOUND:                    "mobile_not_found",
	INVALID_USERNAME:                           "invalid_username",
	CANNOT_ENTER_SAME_EMAIL:                    "please_enter_email_different_from_current_email",
	CANNOT_ENTER_SAME_MOBILE:                   "please_enter_mobile_no_different_from_current_mobile_no",
	MEMBER_USERNAME_ALREADY_EXISTS:             "member_username_already_taken",
	MEMBER_ALREADY_SET_USER_ID:                 "member_user_id_already_set",
	INVALID_SPONSOR:                            "invalid_sponsor",
	INVALID_MACH_CODE:                          "invalid_mach_code",
	INVALID_OLD_PASSWORD:                       "invalid_old_password",
	CHANGE_PASSWORD_OVER_ATTEMPT:               "change_password_over_attempt",
	RESET_PASSWORD_OVER_ATTEMPT:                "reset_password_over_attempt",
	COM_NOT_FOUND:                              "member_com_not_found",
	SPONSOR_ID_NOT_DOWNLINE:                    "sponsor_id_is_not_downline",
	USERNAME_IS_REQUIRED:                       "username_is_required",
	MOBILE_IS_REQUIRED:                         "mobile_is_required",
	INVALID_REFERRAL_CODE:                      "invalid_referral_code",
	GENERATE_REFERRAL_CODE_ERROR:               "generate_referral_code_error",
	GENERATE_MEMBER_SUB_ID_ERROR:               "generate_member_sub_id_error",
	PROFILE_PHOTO_IS_REQUIRED:                  "profile_photo_is_required",
	IMAGE_ONLY_SUPPORT_JPG_AND_PNG_ONLY:        "only_support_jpg_and_png_format",
	CREATE_FILE_ERROR:                          "create_file_error",
	COPY_FILE_ERROR:                            "copy_file_error",
	INVALID_USER_ID:                            "invalid_user_id",
	USER_ID_MUST_CONTAIN_AT_LEAST_ONE_ALPHABET: "user_id_must_contain_at_least_one_alphabet",
	USER_ID_ONLY_ACCEPT_ALPHABET_AND_NUMBER:    "user_id_only_accept_alphabet_and_number",
	USER_ID_CANNOT_CONTAIN_SPACE:               "user_id_cannot_contain_space",
	OS_VERSION_RECORD_NOT_FOUND:                "os_version_record_not_found",
	PROFILE_PIC_SIZE_LIMIT_IS:                  "profile_pic_size_limit_is",
	CONNECTION_NOT_FOUND:                       "connection_not_found",
	INVALID_MEMBER_STATUS:                      "invalid_member_status",

	// admin
	GENERATE_ADMIN_SUB_ID_ERROR:   "generate_admin_sub_id_error",
	INVALID_DATE_FROM_TO_RANGE:    "invalid_date_from_to_range",
	INVALID_DATE_FORMAT:           "invalid_date_format",
	INVALID_SLOT_ROOM_STATUS:      "invalid_status",
	DUPLICATE_SLOT_ROOM:           "duplicate_room",
	DUPLICATE_SLOT_DESC:           "duplicate_desc",
	INVALID_SLOT_ROOM:             "invalid_room_code",
	DUPLICATE_SECTION_DESC:        "duplicate_section",
	INVALID_SLOT_ROW:              "invalid_slot_row",
	INVALID_SLOT_COL:              "invalid_slot_col",
	INVALID_WIN_RATE:              "invalid_win_rate",
	INVALID_WIN_BIG_RATE:          "invalid_win_big_rate",
	DUPLICATE_SLOT_MACH:           "duplicate_mach",
	INVALID_SECTION:               "invalid_section",
	INVALID_SLOT_MACH_TPYE:        "invalid_mach_type",
	INVALID_SYMBOL_CODE:           "invalid_symbol_code",
	INVALID_FILTER_RANGE:          "invalid_filter_range",
	APK_FILE_IS_REQUIRED:          "apk_file_is_required",
	INVALID_VERSION_NUMBER_FORMAT: "invalid_version_number_format",
	VERSION_NUMBER_ALREADY_EXISTS: "version_number_already_exists",
	INVALID_PAY_TOKEN_RANGE:       "invalid_pay_token_range",
	INVALID_PAY_TOKEN_VAL_RANGE:   "invalid_pay_token_value_range",
	INVALID_PAY_TOKEN_COMBINATION: "invalid_pay_token_combinations",
	INVALID_PAY_TOKEN_VAL:         "invalid_pay_token_value",
	INVALID_DATE_RANGE:            "invalid_date_range",
	INVALID_STEP_RANGE:            "invalid_step_range",
	INVALID_STEP_POSITION:         "invalid_step_position",
	REPEATED_PAY_LINE_RULES:       "repeated_pay_line_rules",
	INVALID_ORDER_TYPE:            "invalid_order_type",
	INVALID_PAY_WIN_RATE_RANGE:    "invalid_pay_win_rate_range",

	//slot
	INVALID_TOTAL_BET_LINE:                             "invalid_bet_line_total",
	INVALID_CONFIG_ROW_AND_COLUMN:                      "invalid_config_row_and_column",
	INVALID_CURRBETLINE_NOT_MATCH_PAYTOKEN_AND_PAYLINE: "invalid_current_betline_not_match_paytoken_and_payline",
	PAYLINE_OUT_OF_RANGE:                               "payline_out_of_range",
	FREELINE_OUT_OF_RANGE:                              "free_line_out_of_range",
	INVALID_AT_STOP:                                    "invalid_at_stop",
	INVALID_BET_TOKEN:                                  "invalid_bet_token",
	NOT_FOUND_BET_SIZE:                                 "not_found_rank_bet_size",

	// langage/ translation
	INVALID_LANGUAGE_CODE:           "invalid_language_code",
	TRANSLATION_NAME_ALREADY_EXISTS: "translation_name_already_exists",
	INVALID_TRANSLATION_ID:          "invalid_translation_id",
	DATA_FILE_IS_REQUIRED:           "data_file_is_required",
	DATA_FILE_SHOULD_BE_CSV_FILE:    "data_file_should_be_csv_file",
	DATA_FILE_READ_FILE_ERROR:       "data_file_read_error",

	//base/ media
	REQUEST_API_INVALID_METHOD:   "invalid_method",
	TEXT_PARSE_FAILED:            "text_parse_failed",
	TEXT_EXECUTE_FAILED:          "text_execute_failed",
	MEDIA_URL_NOT_FOUND:          "media_url_not_found",
	MEDIA_PROJECT_CODE_NOT_FOUND: "media_project_code_not_found",
	MEDIA_UPLOAD_FILE_ERROR:      "media_upload_file_error",

	//sicbo
	SICBO_TABLE_NOT_FOUND:               "sicbo_table_not_found",
	TABLE_NO_REACH_MIN_BET:              "no_reach_min_bet",
	TABLE_EXCEED_MAX_BET:                "exceed_max_bet",
	BET_INVALID_TOTAL:                   "bet_invalid_total",
	CELL_BET_REPEATED:                   "cell_bet_repeated",
	CELL_NOT_UNDER_THIS_TABLE:           "cell_not_under_this_table",
	ONLY_ALLOW_BET_ONE_SMALL_OR_BIG:     "only_allow_bet_one_small_or_big",
	SICBO_TABLE_INACTIVE:                "sicbo_table_inactive",
	SICBO_TABLE_EXIST:                   "sicbo_table_exist",
	SICBO_SECTION_INVALID:               "sicbo_section_invalid",
	SICBO_CELL_SETTING_NOT_VALID_LENGTH: "sicbo_cell_setting_not_valid_length",
	SICBO_CELL_SETTING_NOT_VALID:        "sicbo_cell_setting_not_valid",
	ONLY_ALLOW_BET_ONE_ODD_OR_EVEN:      "only_allow_bet_one_odd_or_even",

	//roulette
	ROULETTE_WHEEL_EXIST:                       "roulette_wheel_exist",
	ROULETTE_SECTION_INVALID:                   "roulette_section_invalid",
	ROULETTE_WHEEL_INVALID:                     "roulette_wheel_invalid",
	ROULETTE_WHEEL_INACTIVE:                    "roulette_wheel_inactive",
	ROULETTE_INVALID_TOTAL_COMBINATION_SETTING: "roulette_invalid_total_combination_setting",

	//baccarat
	BACCARAT_TABLE_INVALID:   "baccarat_table_invalid",
	BACCARAT_TABLE_INACTIVE:  "baccarat_table_inactive",
	BACCARAT_TABLE_EXIST:     "baccarat_table_exist",
	BACCARAT_SECTION_INVALID: "baccarat_section_invalid",
	BACCARAT_CELL_INVALID:    "baccarat_cell_invalid",
}

// GetMsg get error information based on Code
func GetMsg(code int) string {
	msg, ok := MsgFlags[code]
	if ok {
		return msg
	}

	return MsgFlags[ERROR]
}
